/**
 * Desktop Viewer entry — session-list sidebar + tiling terminal panes over the
 * Hub (plan §6). This is the desktop capability tier; the PWA tier is chat-only
 * and lands in Phase 5.
 *
 * FIRST-RUN FLOW: instead of a bare hub-URL form, the viewer opens with a
 * welcome screen (onboarding.ts) asking which ROLE this machine plays:
 *
 *   standalone  desktop app starts a local open hub+sessiond+agent; the viewer
 *               connects over loopback with no pin.
 *   hub         desktop app starts a local TRUST-mode hub (this viewer's device
 *               is auto-trusted); the viewer connects with its signer and pins
 *               the hub key, which is surfaced in the sidebar for spokes.
 *   spoke       join an existing hub: a small form collects the remote URL and
 *               hub-key pin. In the desktop app this also starts a local
 *               sessiond+agent so this Mac's shells join the fleet; in a plain
 *               browser the viewer simply connects (remote/spoke use).
 *
 * The choice persists under localStorage 'glass.role' and is reconfigurable at
 * any time via the app's File menu (Tauri 'glass://reconfigure' event) or the
 * sidebar gear — both stop the backend, clear the role, and re-run onboarding.
 * The device identity itself is generated by auth.ts and kept in localStorage.
 * For local development, a `?hub=` query param still connects straight to that
 * hub without touching the stored role.
 */
import { HubClient } from "./hub-client.js";
import { TerminalPane } from "./terminal-pane.js";
import { loadOrCreateIdentity, loadHubConfig, saveHubConfig, type DeviceIdentity, type HubConfig } from "./auth.js";
import { showOnboarding, type Role } from "./onboarding.js";
import { isNative, startBackend, stopBackend, onReconfigure } from "./native.js";
import type { DeviceRecord } from "@glass/protocol";
import "@xterm/xterm/css/xterm.css";
import "./style.css";

const ROLE_KEY = "glass.role";

/** The live client, if the app UI is running — closed on reconfigure. */
let currentClient: HubClient | null = null;

function storedRole(): Role | null {
  const r = localStorage.getItem(ROLE_KEY);
  return r === "standalone" || r === "hub" || r === "spoke" ? r : null;
}

async function main(): Promise<void> {
  const app = document.getElementById("app");
  if (!app) throw new Error("#app missing");

  const identity = await loadOrCreateIdentity();

  // File menu → "Reconfigure…" (desktop shell event). Harmless in a browser.
  try {
    onReconfigure(() => void reconfigure(app, identity));
  } catch {
    /* bridge unavailable — plain browser */
  }

  // Dev convenience: ?hub= connects straight to that hub for this load,
  // without touching the stored role.
  const fromQuery = new URLSearchParams(location.search).get("hub");
  if (fromQuery) {
    saveHubConfig(fromQuery, loadHubConfig()?.hubKeyPin);
    const cfg = loadHubConfig();
    if (cfg) {
      startApp(app, identity, cfg);
      return;
    }
  }

  const role = storedRole();
  if (!role) {
    showOnboarding(app, { onPick: (r) => pickRole(app, identity, r, false) });
    return;
  }
  try {
    await runRole(app, identity, role, true);
  } catch (err) {
    showOnboarding(app, {
      onPick: (r) => pickRole(app, identity, r, false),
      error: `could not start as ${role}: ${err instanceof Error ? err.message : String(err)}`,
    });
  }
}

/**
 * Onboarding pick handler. Thrown errors are displayed by the onboarding
 * screen itself. `reloadAfter` is set when reconfiguring a running app: the
 * new role is persisted and the page reloads so the whole stack re-inits
 * cleanly through the stored-role path.
 */
async function pickRole(app: HTMLElement, identity: DeviceIdentity, role: Role, reloadAfter: boolean): Promise<void> {
  if (role === "spoke") {
    showSpokeScreen(app, identity, reloadAfter);
    return;
  }
  requireNative(role);
  if (reloadAfter) {
    localStorage.setItem(ROLE_KEY, role);
    location.reload();
    return;
  }
  await runRole(app, identity, role, false);
}

function requireNative(role: Role): void {
  if (isNative()) return;
  const name = role === "standalone" ? "Standalone" : "Hub";
  throw new Error(`${name} needs the desktop app — in a browser, pick Spoke to connect to a remote hub.`);
}

/**
 * Bring up the given role and enter the app. Persists the role once the
 * backend is actually up (so a failed first pick doesn't stick). `splash`
 * paints a "starting…" note — only used on the stored-role boot path; from
 * onboarding the picked card shows its own busy state and stays on screen so
 * errors have somewhere to land.
 */
async function runRole(app: HTMLElement, identity: DeviceIdentity, role: Role, splash: boolean): Promise<void> {
  if (role === "spoke") {
    const cfg = loadHubConfig();
    if (!cfg) throw new Error("spoke role has no saved hub connection — pick Spoke again to re-enter it");
    if (isNative()) {
      if (splash) showStarting(app, role);
      await startBackend("spoke", { hubUrl: cfg.hubUrl, ...(cfg.hubKeyPin ? { hubKeyPin: cfg.hubKeyPin } : {}) });
    }
    localStorage.setItem(ROLE_KEY, "spoke");
    startApp(app, identity, cfg);
    return;
  }

  requireNative(role);
  if (splash) showStarting(app, role);
  if (role === "standalone") {
    const res = await startBackend("standalone");
    localStorage.setItem(ROLE_KEY, "standalone");
    // The standalone hub is open (loopback, no auth) — connect with no pin.
    startApp(app, identity, { hubUrl: res.hubUrl });
  } else {
    const res = await startBackend("hub", { deviceId: identity.deviceId, devicePub: identity.publicKey });
    if (!res.hubKey) throw new Error("hub backend did not report its identity key");
    localStorage.setItem(ROLE_KEY, "hub");
    startApp(app, identity, { hubUrl: res.hubUrl, hubKeyPin: res.hubKey }, { hubKey: res.hubKey });
  }
}

/** File menu / gear: stop the backend, forget the role, re-run onboarding. */
async function reconfigure(app: HTMLElement, identity: DeviceIdentity): Promise<void> {
  currentClient?.close();
  currentClient = null;
  if (isNative()) {
    try {
      await stopBackend();
    } catch {
      /* nothing running */
    }
  }
  localStorage.removeItem(ROLE_KEY);
  showOnboarding(app, { onPick: (r) => pickRole(app, identity, r, true) });
}

/** Minimal splash while the local backend comes up on a normal launch. */
function showStarting(app: HTMLElement, role: Role): void {
  app.replaceChildren();
  const screen = document.createElement("div");
  screen.className = "onboard";
  const note = document.createElement("p");
  note.className = "onboard-starting";
  note.textContent = `starting ${role} backend…`;
  screen.append(note);
  app.append(screen);
}

/**
 * The spoke setup screen: remote hub URL + hub-key pin, plus THIS device's
 * public key so the hub operator can trust it:
 *   hub trust add --device-id <id> --name <name> --public-key <key> --roles viewer
 * Leave the pin blank only for a dev --open hub.
 */
function showSpokeScreen(app: HTMLElement, identity: DeviceIdentity, reloadAfter: boolean): void {
  app.replaceChildren();

  const existing = loadHubConfig();
  const screen = document.createElement("div");
  screen.className = "connect";
  const panel = document.createElement("div");
  panel.className = "connect-panel";

  const title = document.createElement("h1");
  title.textContent = "glass";
  const subtitle = document.createElement("p");
  subtitle.className = "connect-subtitle";
  subtitle.textContent = "spoke — join an existing hub";

  // --- hub URL ---
  const urlLabel = document.createElement("label");
  urlLabel.textContent = "hub url";
  const urlInput = document.createElement("input");
  urlInput.type = "text";
  urlInput.placeholder = "wss://hub.example.net:8787";
  urlInput.value = existing?.hubUrl ?? "ws://127.0.0.1:8787";
  urlInput.spellcheck = false;

  // --- hub-key pin ---
  const pinLabel = document.createElement("label");
  pinLabel.textContent = "hub key (pin)";
  const pinInput = document.createElement("input");
  pinInput.type = "text";
  pinInput.placeholder = "hub public key — blank only for a dev --open hub";
  pinInput.value = existing?.hubKeyPin ?? "";
  pinInput.spellcheck = false;
  const pinHint = document.createElement("p");
  pinHint.className = "connect-hint";
  pinHint.textContent = "shown in the hub app's sidebar as “hub key — pin this on spokes”";

  // --- THIS device's public key, prominently, with copy ---
  const keyBlock = document.createElement("div");
  keyBlock.className = "device-key";
  const keyTitle = document.createElement("div");
  keyTitle.className = "device-key-title";
  keyTitle.textContent = `this device — ${identity.deviceId}`;
  const keyRow = document.createElement("div");
  keyRow.className = "device-key-row";
  const keyCode = document.createElement("code");
  keyCode.textContent = identity.publicKey;
  const copyBtn = document.createElement("button");
  copyBtn.textContent = "copy";
  copyBtn.addEventListener("click", () => {
    void navigator.clipboard.writeText(identity.publicKey).then(() => {
      copyBtn.textContent = "copied";
      setTimeout(() => (copyBtn.textContent = "copy"), 1500);
    });
  });
  keyRow.append(keyCode, copyBtn);
  const keyHint = document.createElement("p");
  keyHint.className = "connect-hint";
  keyHint.textContent = `trust it on the hub:  hub trust add --device-id ${identity.deviceId} --name "This device" --public-key <key> --roles viewer`;
  keyBlock.append(keyTitle, keyRow, keyHint);

  // --- connect / back ---
  const error = document.createElement("p");
  error.className = "connect-error";
  const buttons = document.createElement("div");
  buttons.className = "connect-buttons";
  const connectBtn = document.createElement("button");
  connectBtn.className = "connect-go";
  connectBtn.textContent = "connect";
  const backBtn = document.createElement("button");
  backBtn.className = "connect-back";
  backBtn.textContent = "back";
  backBtn.addEventListener("click", () => {
    showOnboarding(app, { onPick: (r) => pickRole(app, identity, r, reloadAfter) });
  });
  buttons.append(connectBtn, backBtn);

  const submit = async (): Promise<void> => {
    const hubUrl = urlInput.value.trim();
    if (!/^wss?:\/\//.test(hubUrl)) {
      error.textContent = "hub url must start with ws:// or wss://";
      return;
    }
    const pin = pinInput.value.trim();
    error.textContent = "";
    connectBtn.disabled = true;
    backBtn.disabled = true;
    try {
      if (isNative()) {
        // Also join this Mac's shells to the fleet via the local backend.
        connectBtn.textContent = "starting…";
        await startBackend("spoke", { hubUrl, ...(pin ? { hubKeyPin: pin } : {}) });
      }
      saveHubConfig(hubUrl, pin || undefined);
      localStorage.setItem(ROLE_KEY, "spoke");
      if (reloadAfter) {
        location.reload();
        return;
      }
      startApp(app, identity, pin ? { hubUrl, hubKeyPin: pin } : { hubUrl });
    } catch (err) {
      error.textContent = err instanceof Error ? err.message : String(err);
      connectBtn.disabled = false;
      backBtn.disabled = false;
      connectBtn.textContent = "connect";
    }
  };
  connectBtn.addEventListener("click", () => void submit());
  panel.addEventListener("keydown", (ev) => {
    if (ev.key === "Enter" && (ev.target === urlInput || ev.target === pinInput)) void submit();
  });

  panel.append(title, subtitle, urlLabel, urlInput, pinLabel, pinInput, pinHint, keyBlock, error, buttons);
  screen.append(panel);
  app.append(screen);
  urlInput.focus();
}

function startApp(app: HTMLElement, identity: DeviceIdentity, config: HubConfig, extras?: { hubKey?: string }): void {
  app.replaceChildren();

  const sidebar = document.createElement("aside");
  sidebar.className = "sidebar";
  const status = document.createElement("div");
  status.className = "status";
  const statusText = document.createElement("span");
  statusText.className = "status-text";
  const settingsBtn = document.createElement("button");
  settingsBtn.className = "settings";
  settingsBtn.textContent = "⚙";
  settingsBtn.title = "reconfigure (choose role again)";
  settingsBtn.addEventListener("click", () => {
    void reconfigure(app, identity);
  });
  status.append(statusText, settingsBtn);
  sidebar.append(status);

  // Hub role: surface the hub identity key unobtrusively so the operator can
  // pin it when setting up spokes.
  if (extras?.hubKey) {
    const chip = document.createElement("div");
    chip.className = "hubkey";
    const chipTitle = document.createElement("div");
    chipTitle.className = "hubkey-title";
    chipTitle.textContent = "hub key — pin this on spokes";
    const chipRow = document.createElement("div");
    chipRow.className = "hubkey-row";
    const chipCode = document.createElement("code");
    chipCode.textContent = extras.hubKey;
    const chipCopy = document.createElement("button");
    chipCopy.textContent = "copy";
    chipCopy.addEventListener("click", () => {
      void navigator.clipboard.writeText(extras.hubKey ?? "").then(() => {
        chipCopy.textContent = "copied";
        setTimeout(() => (chipCopy.textContent = "copy"), 1500);
      });
    });
    chipRow.append(chipCode, chipCopy);
    chip.append(chipTitle, chipRow);
    sidebar.append(chip);
  }

  const deviceList = document.createElement("div");
  deviceList.className = "devices";
  sidebar.append(deviceList);

  const grid = document.createElement("main");
  grid.className = "grid";

  app.append(sidebar, grid);

  const panes = new Map<string, TerminalPane>();
  const client = new HubClient(
    config.hubUrl,
    identity.deviceId,
    "This device",
    {
      onConnected: () => {
        statusText.textContent = `connected as ${identity.deviceId}`;
        status.dataset["state"] = "connected";
        void refreshDevices();
      },
      onDisconnected: () => {
        statusText.textContent = "reconnecting…";
        status.dataset["state"] = "waiting";
      },
      onDevices: renderDevices,
      onDeviceState: () => void refreshDevices(),
      onScrollback: (sid, sb) => panes.get(sid)?.reset(sb),
      onOutput: (sid, data) => panes.get(sid)?.write(data),
      onExited: (sid) => {
        panes.get(sid)?.markDead("session exited");
      },
      onError: (code, message) => {
        statusText.textContent = `error: ${code} — ${message}`;
        if (code === "hub_identity") status.dataset["state"] = "error";
      },
    },
    identity,
    config.hubKeyPin,
  );
  currentClient = client;

  async function refreshDevices(): Promise<void> {
    try {
      renderDevices(await client.listDevices());
    } catch {
      /* not connected yet */
    }
  }

  function renderDevices(devices: DeviceRecord[]): void {
    deviceList.replaceChildren();
    const agents = devices.filter((d) => d.roles.includes("agent"));
    if (agents.length === 0) {
      const empty = document.createElement("div");
      empty.className = "empty";
      empty.textContent = "no agents online";
      deviceList.append(empty);
      return;
    }
    for (const agent of agents) {
      const row = document.createElement("div");
      row.className = "device";
      row.dataset["state"] = agent.state;

      const name = document.createElement("span");
      name.className = "device-name";
      name.textContent = agent.name;

      const dot = document.createElement("span");
      dot.className = "dot";
      dot.title = agent.state;

      const newShell = document.createElement("button");
      newShell.textContent = "+ shell";
      newShell.disabled = agent.state !== "connected";
      newShell.addEventListener("click", () => void openShell(agent.id, agent.name));

      row.append(dot, name, newShell);
      deviceList.append(row);
    }
  }

  async function openShell(agentId: string, agentName: string): Promise<void> {
    try {
      const session = await client.createSession(agentId, { kind: "pty" });
      const pane = new TerminalPane(client, agentId, session.id, `${agentName} · ${session.title}`);
      panes.set(session.id, pane);
      grid.append(pane.el);
      pane.refit();
    } catch (err) {
      statusText.textContent = `could not open shell: ${String(err)}`;
    }
  }

  client.connect();
}

void main();
