/**
 * Desktop Viewer entry — session-list sidebar + tiling terminal panes over the
 * Hub (plan §6). This is the desktop capability tier; the PWA tier is chat-only
 * and lands in Phase 5.
 *
 * FIRST-RUN FLOW: instead of a bare hub-URL form, the viewer opens with a
 * welcome screen (onboarding.ts) asking which ROLE this machine plays:
 *
 *   standalone  desktop app starts a local open hub+sessiond+agent; the viewer
 *               connects over loopback with no pin.
 *   hub         desktop app starts a local TRUST-mode hub (this viewer's device
 *               is auto-trusted); the viewer connects with its signer and pins
 *               the hub key, which is surfaced in the sidebar for spokes.
 *   spoke       join an existing hub: a small form collects the remote URL and
 *               hub-key pin. In the desktop app this also starts a local
 *               sessiond+agent so this Mac's shells join the fleet; in a plain
 *               browser the viewer simply connects (remote/spoke use).
 *
 * The choice persists under localStorage 'glass.role' and is reconfigurable at
 * any time via the app's File menu (Tauri 'glass://reconfigure' event) or the
 * sidebar gear — both stop the backend, clear the role, and re-run onboarding.
 * The device identity itself is generated by auth.ts and kept in localStorage.
 * For local development, a `?hub=` query param still connects straight to that
 * hub without touching the stored role.
 */
import { HubClient, type EnrollConfig } from "./hub-client.js";
import { Workspace, SESSION_MIME } from "./workspace.js";
import { AgentBoard } from "./agent-board.js";
import { loadOrCreateIdentity, loadHubConfig, saveHubConfig, type DeviceIdentity, type HubConfig } from "./auth.js";
import { showOnboarding, type Role } from "./onboarding.js";
import { isNative, startBackend, stopBackend, onReconfigure, onSettings, checkForUpdates, appVersion, launchProxiedBrowser, type BackendInfo } from "./native.js";
import { openTerminalSettings } from "./settings-ui.js";
import { cmpVersions } from "./update-policy.js";
import { createRibbon } from "./ribbon.js";
import { skillInput, type Skill } from "./skills.js";
import { loadSkills, openSkillsEditor } from "./skills-ui.js";
import { ExtensionHost } from "./extension-host.js";
import { loadExtensions, openExtensionsManager } from "./extensions-ui.js";
import { IMessagePanel } from "./imessage-panel.js";
import { DeviceId, type DeviceRecord, type DeviceRole, type EnrollCompanion } from "@glass/protocol";

/** Build the enrollment config for a spoke: enroll the viewer, with the local
 *  shell-agent as a companion so one approval trusts the whole Mac. */
function spokeEnroll(res?: BackendInfo): EnrollConfig {
  const companions: EnrollCompanion[] =
    res?.agentId && res.agentPub ? [{ deviceId: DeviceId.parse(res.agentId), publicKey: res.agentPub, roles: ["agent"] }] : [];
  return { deviceName: res?.agentName || "This device", roles: ["viewer"], companions };
}

/** A friendly label for a served-PWA device, shown to the approver during
 *  enrollment (the phone/tablet has no local backend to name it). */
function browserDeviceName(): string {
  const ua = navigator.userAgent;
  if (/iPhone/.test(ua)) return "iPhone";
  if (/iPad/.test(ua)) return "iPad";
  if (/iPod/.test(ua)) return "iPod touch";
  if (/Android/.test(ua)) return "Android device";
  if (/Macintosh/.test(ua)) return "Mac (browser)";
  if (/Windows/.test(ua)) return "Windows (browser)";
  return "Browser";
}
import "@xterm/xterm/css/xterm.css";
import "./style.css";

const ROLE_KEY = "glass.role";

/** The live client, if the app UI is running — closed on reconfigure. */
let currentClient: HubClient | null = null;

function storedRole(): Role | null {
  const r = localStorage.getItem(ROLE_KEY);
  return r === "standalone" || r === "hub" || r === "spoke" ? r : null;
}

async function main(): Promise<void> {
  const app = document.getElementById("app");
  if (!app) throw new Error("#app missing");

  // Auto-update (desktop): pull + apply a newer signed build and relaunch — no
  // manual reinstall. Spokes/standalone reach the update origin (a REMOTE hub,
  // already up) immediately, so they check now. The HUB updates itself through
  // its OWN relay tunnel, which isn't up until startBackend() below — so it
  // defers its check to runRole()'s hub branch. Fails open offline.
  if (isNative() && storedRole() !== "hub") {
    const relaunching = await checkForUpdates((msg) => showUpdating(app, msg));
    if (relaunching) return; // a relaunch into the new version is under way
  }

  const identity = await loadOrCreateIdentity();

  // File menu → "Reconfigure…" (desktop shell event). Harmless in a browser.
  try {
    onReconfigure(() => void reconfigure(app, identity));
  } catch {
    /* bridge unavailable — plain browser */
  }

  // File menu → "Terminal Settings…" (desktop shell event). No-op in a browser.
  try {
    onSettings(() => openTerminalSettings());
  } catch {
    /* bridge unavailable — plain browser */
  }

  // PWA tier: register the service worker only when this bundle is served over
  // http(s) in a real browser — the Tauri shell must never run one (it loads
  // from its own scheme and manages its own bundle).
  if (!isNative() && "serviceWorker" in navigator && /^https?:$/.test(location.protocol)) {
    void navigator.serviceWorker.register("/sw.js").catch(() => {
      /* SW is progressive enhancement — the app works without it */
    });
  }

  // Dev convenience: ?hub= connects straight to that hub for this load,
  // without touching the stored role.
  const fromQuery = new URLSearchParams(location.search).get("hub");
  if (fromQuery) {
    saveHubConfig(fromQuery, loadHubConfig()?.hubKeyPin);
    const cfg = loadHubConfig();
    if (cfg) {
      startApp(app, identity, cfg);
      return;
    }
  }

  const role = storedRole();

  // PWA tier: when the viewer is SERVED (by the hub, not the desktop shell)
  // and nothing is configured yet, default the hub connection to the serving
  // origin so an installed home-screen app just connects. A stored role or
  // hub config (e.g. a browser used as a spoke) still wins, and the desktop
  // role flow below is untouched.
  if (!role && !isNative() && !loadHubConfig() && /^https?:$/.test(location.protocol)) {
    const hubUrl = `${location.protocol === "https:" ? "wss" : "ws"}://${location.host}`;
    // A freshly-installed PWA (e.g. on an iPhone) isn't trusted yet. Give it an
    // enroll config so it self-enrolls as a viewer — shows a 6-digit code the
    // owner approves on a trusted device — instead of reconnect-looping on 4007.
    // No hub-key pin: the wss cert authenticates the hub, and the join is still
    // gated by the owner reading + typing the code (number match). Once trusted,
    // the enroll config is inert (only used when the hub refuses us).
    const enroll: EnrollConfig = { deviceName: browserDeviceName(), roles: ["viewer"], companions: [] };
    startApp(app, identity, { hubUrl }, undefined, enroll);
    return;
  }

  if (!role) {
    showOnboarding(app, { onPick: (r) => pickRole(app, identity, r, false) });
    return;
  }
  try {
    await runRole(app, identity, role, true);
  } catch (err) {
    showOnboarding(app, {
      onPick: (r) => pickRole(app, identity, r, false),
      error: `could not start as ${role}: ${err instanceof Error ? err.message : String(err)}`,
    });
  }
}

/**
 * Onboarding pick handler. Thrown errors are displayed by the onboarding
 * screen itself. `reloadAfter` is set when reconfiguring a running app: the
 * new role is persisted and the page reloads so the whole stack re-inits
 * cleanly through the stored-role path.
 */
async function pickRole(app: HTMLElement, identity: DeviceIdentity, role: Role, reloadAfter: boolean): Promise<void> {
  if (role === "spoke") {
    showSpokeScreen(app, identity, reloadAfter);
    return;
  }
  requireNative(role);
  if (reloadAfter) {
    localStorage.setItem(ROLE_KEY, role);
    location.reload();
    return;
  }
  await runRole(app, identity, role, false);
}

function requireNative(role: Role): void {
  if (isNative()) return;
  const name = role === "standalone" ? "Standalone" : "Hub";
  throw new Error(`${name} needs the desktop app — in a browser, pick Spoke to connect to a remote hub.`);
}

/**
 * Bring up the given role and enter the app. Persists the role once the
 * backend is actually up (so a failed first pick doesn't stick). `splash`
 * paints a "starting…" note — only used on the stored-role boot path; from
 * onboarding the picked card shows its own busy state and stays on screen so
 * errors have somewhere to land.
 */
async function runRole(app: HTMLElement, identity: DeviceIdentity, role: Role, splash: boolean): Promise<void> {
  if (role === "spoke") {
    const cfg = loadHubConfig();
    if (!cfg) throw new Error("spoke role has no saved hub connection — pick Spoke again to re-enter it");
    let res: BackendInfo | undefined;
    if (isNative()) {
      if (splash) showStarting(app, role);
      res = await startBackend("spoke", { hubUrl: cfg.hubUrl, ...(cfg.hubKeyPin ? { hubKeyPin: cfg.hubKeyPin } : {}) });
    }
    localStorage.setItem(ROLE_KEY, "spoke");
    startApp(app, identity, cfg, res?.agentId ? { localAgentId: res.agentId } : undefined, spokeEnroll(res));
    return;
  }

  requireNative(role);
  if (splash) showStarting(app, role);
  if (role === "standalone") {
    const res = await startBackend("standalone");
    localStorage.setItem(ROLE_KEY, "standalone");
    // The standalone hub is open (loopback, no auth) — connect with no pin.
    startApp(app, identity, { hubUrl: res.hubUrl }, { localAgentId: res.agentId ?? "local" });
  } else {
    const res = await startBackend("hub", { deviceId: identity.deviceId, devicePub: identity.publicKey });
    if (!res.hubKey) throw new Error("hub backend did not report its identity key");
    localStorage.setItem(ROLE_KEY, "hub");
    // Now that the hub backend is up and its relay tunnel is dialing, run the
    // deferred auto-update check the top of main() skipped for the hub. Retry a
    // few times to catch the tunnel as it finishes connecting (the hub reaches
    // its own update origin only through that tunnel). Relaunch if newer.
    if (isNative()) {
      const relaunching = await checkForUpdates((msg) => showUpdating(app, msg), { attempts: 5, delayMs: 2000 });
      if (relaunching) return;
    }
    startApp(app, identity, { hubUrl: res.hubUrl, hubKeyPin: res.hubKey }, { hubKey: res.hubKey, localAgentId: res.agentId ?? "hub-agent" });
  }
}

/** File menu / gear: explicitly stop the persistent backend, forget the role,
 * and re-run onboarding. This is the user-selected destructive session boundary. */
async function reconfigure(app: HTMLElement, identity: DeviceIdentity): Promise<void> {
  currentClient?.close();
  currentClient = null;
  if (isNative()) {
    try {
      await stopBackend();
    } catch {
      /* nothing running */
    }
  }
  localStorage.removeItem(ROLE_KEY);
  showOnboarding(app, { onPick: (r) => pickRole(app, identity, r, true) });
}

/** Splash shown while a signed auto-update downloads + installs before relaunch. */
function showUpdating(app: HTMLElement, msg: string): void {
  app.replaceChildren();
  const screen = document.createElement("div");
  screen.className = "onboard";
  const note = document.createElement("p");
  note.className = "onboard-starting";
  note.textContent = msg;
  screen.append(note);
  app.append(screen);
}

/** Minimal splash while the local backend comes up on a normal launch. */
function showStarting(app: HTMLElement, role: Role): void {
  app.replaceChildren();
  const screen = document.createElement("div");
  screen.className = "onboard";
  const note = document.createElement("p");
  note.className = "onboard-starting";
  note.textContent = `starting ${role} backend…`;
  screen.append(note);
  app.append(screen);
}

/**
 * The spoke setup screen: remote hub URL + hub-key pin, plus THIS device's
 * public key so the hub operator can trust it:
 *   hub trust add --device-id <id> --name <name> --public-key <key> --roles viewer
 * Leave the pin blank only for a dev --open hub.
 */
function showSpokeScreen(app: HTMLElement, identity: DeviceIdentity, reloadAfter: boolean): void {
  app.replaceChildren();

  const existing = loadHubConfig();
  const screen = document.createElement("div");
  screen.className = "connect";
  const panel = document.createElement("div");
  panel.className = "connect-panel";

  const title = document.createElement("h1");
  title.textContent = "Glass";
  const subtitle = document.createElement("p");
  subtitle.className = "connect-subtitle";
  subtitle.textContent = "spoke — join an existing hub";

  // --- hub URL ---
  const urlLabel = document.createElement("label");
  urlLabel.textContent = "hub url";
  const urlInput = document.createElement("input");
  urlInput.type = "text";
  urlInput.placeholder = "wss://hub.example.net:8787";
  urlInput.value = existing?.hubUrl ?? "ws://127.0.0.1:8787";
  urlInput.spellcheck = false;

  // --- hub-key pin ---
  const pinLabel = document.createElement("label");
  pinLabel.textContent = "hub key (pin)";
  const pinInput = document.createElement("input");
  pinInput.type = "text";
  pinInput.placeholder = "hub public key — blank only for a dev --open hub";
  pinInput.value = existing?.hubKeyPin ?? "";
  pinInput.spellcheck = false;
  const pinHint = document.createElement("p");
  pinHint.className = "connect-hint";
  pinHint.textContent = "shown in the hub app's sidebar as “hub key — pin this on spokes”";

  // --- THIS device's public key, prominently, with copy ---
  const keyBlock = document.createElement("div");
  keyBlock.className = "device-key";
  const keyTitle = document.createElement("div");
  keyTitle.className = "device-key-title";
  keyTitle.textContent = `this device — ${identity.deviceId}`;
  const keyRow = document.createElement("div");
  keyRow.className = "device-key-row";
  const keyCode = document.createElement("code");
  keyCode.textContent = identity.publicKey;
  const copyBtn = document.createElement("button");
  copyBtn.textContent = "copy";
  copyBtn.addEventListener("click", () => {
    void navigator.clipboard.writeText(identity.publicKey).then(() => {
      copyBtn.textContent = "copied";
      setTimeout(() => (copyBtn.textContent = "copy"), 1500);
    });
  });
  keyRow.append(keyCode, copyBtn);
  const keyHint = document.createElement("p");
  keyHint.className = "connect-hint";
  keyHint.textContent = `trust it on the hub:  hub trust add --device-id ${identity.deviceId} --name "This device" --public-key <key> --roles viewer`;
  keyBlock.append(keyTitle, keyRow, keyHint);

  // --- connect / back ---
  const error = document.createElement("p");
  error.className = "connect-error";
  const buttons = document.createElement("div");
  buttons.className = "connect-buttons";
  const connectBtn = document.createElement("button");
  connectBtn.className = "connect-go";
  connectBtn.textContent = "connect";
  const backBtn = document.createElement("button");
  backBtn.className = "connect-back";
  backBtn.textContent = "back";
  backBtn.addEventListener("click", () => {
    showOnboarding(app, { onPick: (r) => pickRole(app, identity, r, reloadAfter) });
  });
  buttons.append(connectBtn, backBtn);

  const submit = async (): Promise<void> => {
    const hubUrl = urlInput.value.trim();
    if (!/^wss?:\/\//.test(hubUrl)) {
      error.textContent = "hub url must start with ws:// or wss://";
      return;
    }
    const pin = pinInput.value.trim();
    if (!pin) {
      // The pin authenticates the hub; without it a spoke over the relay has no
      // defense against a man-in-the-middle. The backend refuses too — mirror it here.
      error.textContent = "hub key is required — paste the key shown on the hub";
      return;
    }
    error.textContent = "";
    connectBtn.disabled = true;
    backBtn.disabled = true;
    try {
      let res: BackendInfo | undefined;
      if (isNative()) {
        // Also join this Mac's shells to the fleet via the local backend.
        connectBtn.textContent = "starting…";
        res = await startBackend("spoke", { hubUrl, hubKeyPin: pin });
      }
      saveHubConfig(hubUrl, pin);
      localStorage.setItem(ROLE_KEY, "spoke");
      if (reloadAfter) {
        location.reload();
        return;
      }
      startApp(app, identity, { hubUrl, hubKeyPin: pin }, undefined, spokeEnroll(res));
    } catch (err) {
      error.textContent = err instanceof Error ? err.message : String(err);
      connectBtn.disabled = false;
      backBtn.disabled = false;
      connectBtn.textContent = "connect";
    }
  };
  connectBtn.addEventListener("click", () => void submit());
  panel.addEventListener("keydown", (ev) => {
    if (ev.key === "Enter" && (ev.target === urlInput || ev.target === pinInput)) void submit();
  });

  panel.append(title, subtitle, urlLabel, urlInput, pinLabel, pinInput, pinHint, keyBlock, error, buttons);
  screen.append(panel);
  app.append(screen);
  urlInput.focus();
}

function startApp(
  app: HTMLElement,
  identity: DeviceIdentity,
  config: HubConfig,
  /** hubKey: surfaced in the sidebar for spokes. localAgentId: the agent on
   *  THIS Mac — required for "browse via device" (it hosts the local SOCKS
   *  forwarder); absent in a plain browser / PWA, which hides the feature. */
  extras?: { hubKey?: string; localAgentId?: string },
  enroll?: EnrollConfig,
): void {
  app.replaceChildren();

  const sidebar = document.createElement("aside");
  sidebar.className = "sidebar";
  const status = document.createElement("div");
  status.className = "status";
  const statusText = document.createElement("span");
  statusText.className = "status-text";
  const termPrefsBtn = document.createElement("button");
  termPrefsBtn.className = "settings";
  termPrefsBtn.textContent = "Aa";
  termPrefsBtn.title = "terminal settings (fonts, colours, background)";
  termPrefsBtn.addEventListener("click", () => {
    openTerminalSettings();
  });
  const settingsBtn = document.createElement("button");
  settingsBtn.className = "settings";
  settingsBtn.textContent = "⚙";
  settingsBtn.title = "reconfigure (choose role again)";
  settingsBtn.addEventListener("click", () => {
    void reconfigure(app, identity);
  });
  status.append(statusText, termPrefsBtn, settingsBtn);
  sidebar.append(status);

  // Hub role: surface the hub identity key unobtrusively so the operator can
  // pin it when setting up spokes.
  if (extras?.hubKey) {
    const chip = document.createElement("div");
    chip.className = "hubkey";
    const chipTitle = document.createElement("div");
    chipTitle.className = "hubkey-title";
    chipTitle.textContent = "hub key — pin this on spokes";
    const chipRow = document.createElement("div");
    chipRow.className = "hubkey-row";
    const chipCode = document.createElement("code");
    chipCode.textContent = extras.hubKey;
    const chipCopy = document.createElement("button");
    chipCopy.textContent = "copy";
    chipCopy.addEventListener("click", () => {
      void navigator.clipboard.writeText(extras.hubKey ?? "").then(() => {
        chipCopy.textContent = "copied";
        setTimeout(() => (chipCopy.textContent = "copy"), 1500);
      });
    });
    chipRow.append(chipCode, chipCopy);
    chip.append(chipTitle, chipRow);
    sidebar.append(chip);
  }

  const deviceList = document.createElement("div");
  deviceList.className = "devices";
  sidebar.append(deviceList);

  // Version footer — flips visibly when an auto-update lands (native only).
  const versionFoot = document.createElement("div");
  versionFoot.className = "version-foot";
  sidebar.append(versionFoot);

  // Update-available banner (native only). The hub pushes `update.available` with
  // the version at its origin; we nag ONLY when it's strictly newer than what we
  // run. The button applies the signed update and relaunches; on the new version
  // the hub's next push equals our version, so the banner clears itself.
  let runningVersion = "";
  let offeredVersion = "";
  let offeredNotes = "";
  let updating = false;
  let errored = false;
  const updateBanner = document.createElement("div");
  updateBanner.className = "update-banner";
  updateBanner.hidden = true;
  const bannerText = document.createElement("span");
  bannerText.className = "update-banner-text";
  const bannerBtn = document.createElement("button");
  bannerBtn.className = "update-banner-btn";
  bannerBtn.textContent = "Restart to update";
  bannerBtn.addEventListener("click", () => void applyUpdate());
  // "What's changed" opens the release's change notes (pushed by the hub from
  // the manifest). Shown only when the offered release actually carries notes.
  const bannerNotesBtn = document.createElement("button");
  bannerNotesBtn.className = "update-banner-btn";
  bannerNotesBtn.textContent = "What's changed";
  bannerNotesBtn.hidden = true;
  bannerNotesBtn.addEventListener("click", () => showChangeNotes());
  updateBanner.append(bannerText, bannerBtn, bannerNotesBtn);

  // In-app modal with the offered release's change notes. Notes originate from
  // the update origin's manifest, so they are untrusted display text: rendered
  // via textContent only, never as markup.
  let notesOverlay: HTMLElement | undefined;
  function showChangeNotes(): void {
    notesOverlay?.remove();
    const overlay = document.createElement("div");
    overlay.className = "tset-overlay";
    const panel = document.createElement("div");
    panel.className = "tset-panel";
    panel.setAttribute("role", "dialog");
    panel.tabIndex = -1;
    const title = document.createElement("h2");
    title.className = "tset-title";
    title.textContent = `glass ${offeredVersion} — what's changed`;
    const body = document.createElement("div");
    body.className = "notes-body";
    body.textContent = offeredNotes || "No change notes for this release.";
    const closeBtn = document.createElement("button");
    closeBtn.className = "update-banner-btn";
    closeBtn.textContent = "Close";
    const close = (): void => {
      overlay.remove();
      notesOverlay = undefined;
    };
    closeBtn.addEventListener("click", close);
    overlay.addEventListener("mousedown", (ev) => {
      if (ev.target === overlay) close();
    });
    panel.addEventListener("keydown", (ev) => {
      if (ev.key === "Escape") close();
    });
    panel.append(title, body, closeBtn);
    overlay.append(panel);
    document.body.append(overlay);
    notesOverlay = overlay;
    panel.focus();
  }

  function refreshUpdateBanner(): void {
    // While an update is in flight OR has just failed, applyUpdate() owns the
    // banner's text (progress / error + Retry) — keep it visible and don't
    // clobber it. This is what stops a mid-update hub push from hiding a failure
    // and stranding the Retry button.
    if (updating || errored) {
      updateBanner.hidden = false;
      return;
    }
    const newer = !!runningVersion && !!offeredVersion && cmpVersions(offeredVersion, runningVersion) > 0;
    updateBanner.hidden = !(isNative() && newer);
    if (!updateBanner.hidden) {
      bannerText.textContent = `Glass ${offeredVersion} is available.`;
      bannerBtn.textContent = "Restart to update";
      bannerBtn.disabled = false;
      bannerNotesBtn.hidden = !offeredNotes;
    }
  }

  async function applyUpdate(): Promise<void> {
    if (updating) return;
    updating = true;
    errored = false;
    bannerBtn.disabled = true;
    bannerText.textContent = "Updating…";
    updateBanner.hidden = false;
    // On success this verifies + installs the signed build and relaunches — it
    // never returns here. onError sets the visible error state so a failure and
    // its Retry button survive any concurrent hub push.
    const ok = await checkForUpdates((msg) => (bannerText.textContent = msg), {
      attempts: 3,
      delayMs: 2000,
      onError: (msg) => {
        updating = false;
        errored = true;
        bannerText.textContent = msg;
        bannerBtn.textContent = "Retry";
        bannerBtn.disabled = false;
        updateBanner.hidden = false;
      },
    });
    if (!ok) {
      updating = false;
      // If onError fired, `errored` keeps the failure visible. Otherwise this was
      // "reachable but nothing to install" (rare race) — clear and re-evaluate.
      if (!errored) refreshUpdateBanner();
    }
  }

  if (isNative()) {
    void appVersion()
      .then((v) => {
        runningVersion = v;
        versionFoot.textContent = `Glass ${v}`;
        refreshUpdateBanner();
      })
      .catch(() => undefined);
  }

  let workspace: Workspace;
  let agentBoard: AgentBoard;
  let latestDevices: DeviceRecord[] = [];
  let didAutoOpen = false;
  // Sessions that exist on agents but this viewer has NOT attached — discovered
  // via listSessions on connect and live session.created broadcasts. Shown in the
  // sidebar; clicking one attaches it. sessionId -> { agentId, title }.
  const remote = new Map<string, { agentId: string; title: string }>();

  const client = new HubClient(
    config.hubUrl,
    identity.deviceId,
    "This device",
    {
      onConnected: () => {
        statusText.textContent = `connected as ${identity.deviceId}`;
        status.dataset["state"] = "connected";
        void refreshDevices();
        void refreshRuns();
      },
      onDisconnected: () => {
        statusText.textContent = "reconnecting…";
        status.dataset["state"] = "waiting";
      },
      onDevices: (devices) => {
        latestDevices = devices;
        renderSidebar();
      },
      onDeviceState: () => void refreshDevices(),
      onScrollback: (sid, sb) => workspace.reset(sid, sb),
      onOutput: (sid, data) => {
        workspace.write(sid, data);
        extHost.emitOutput(sid, data); // extensions holding sessions.read + watching
      },
      onExited: (sid) => {
        remote.delete(sid);
        workspace.markDead(sid, "session exited");
        renderSidebar();
      },
      onSessionAppeared: (session) => {
        // A shell opened elsewhere in the fleet. Track it as attachable unless we
        // already hold it (e.g. the broadcast echo of a shell we just created).
        if (!workspace.has(session.id) && !remote.has(session.id)) {
          remote.set(session.id, { agentId: session.deviceId, title: session.title });
          renderSidebar();
        }
      },
      onSessionRenamed: (session) => {
        // A session was renamed somewhere in the fleet (possibly by us — the
        // broadcast echoes back). Sync pane header + sidebar entry.
        workspace.rename(session.id, session.title);
        const r = remote.get(session.id);
        if (r) r.title = session.title;
        renderSidebar();
      },
      onRunAppeared: (run) => {
        agentBoard.upsert(run);
      },
      onRunUpdated: (run) => agentBoard.upsert(run),
      onRunEvent: (event) => agentBoard.append(event),
      onWorkspaces: (workspaces) => agentBoard.restore(workspaces),
      onError: (code, message) => {
        statusText.textContent = `error: ${code} — ${message}`;
        if (code === "hub_identity") status.dataset["state"] = "error";
      },
      onUpdateAvailable: (version, notes) => {
        offeredVersion = version;
        offeredNotes = notes ?? "";
        refreshUpdateBanner();
      },
      onIMessageNew: (agentId, message) => msgPanel.onNew(agentId, message),
      // --- enrollment ---
      onEnrollWaiting: (code) => showJoinWaiting(code),          // this device is joining
      onEnrollApproved: () => clearJoinOverlay(),                 // trusted now; client reconnects
      onEnrollDenied: () => showJoinDenied(),
      onEnrollRequest: (req) => showApprovalPrompt(req),          // another device wants in
    },
    identity,
    config.hubKeyPin,
    enroll,
  );
  currentClient = client;

  workspace = new Workspace(client, () => renderSidebar());
  agentBoard = new AgentBoard(client);

  const boardBtn = document.createElement("button");
  boardBtn.className = "agent-board-toggle";
  boardBtn.textContent = "Agent Board";
  boardBtn.addEventListener("click", () => {
    const show = !agentBoard.visible;
    agentBoard.show(show);
    workspace.el.hidden = show;
    boardBtn.dataset["active"] = String(show);
    app.classList.remove("drawer-open");
  });
  sidebar.insertBefore(boardBtn, deviceList);

  // Mobile (<720px, style.css): the sidebar becomes a slide-out drawer. The
  // hamburger + backdrop are display:none on desktop and position:fixed, so
  // they never affect the desktop grid layout.
  const menuBtn = document.createElement("button");
  menuBtn.className = "menu-toggle";
  menuBtn.textContent = "☰";
  menuBtn.title = "sessions";
  menuBtn.setAttribute("aria-label", "toggle session sidebar");
  menuBtn.addEventListener("click", () => app.classList.toggle("drawer-open"));
  const backdrop = document.createElement("div");
  backdrop.className = "drawer-backdrop";
  backdrop.addEventListener("click", () => app.classList.remove("drawer-open"));

  // Right-side ribbon (customizable widget dock). Built-in widgets would call
  // ribbon.register({ id, title, icon, activate }) here; today the available
  // list is the user's own skills — scripts whose ribbon button types them
  // into the FOCUSED session (exactly like typing; a skill can't do anything
  // the keyboard can't, and there's no active session -> it's a no-op).
  const knownSkills = new Set<string>();
  const registerSkill = (skill: Skill): void => {
    knownSkills.add(skill.id);
    ribbon.register({
      id: skill.id,
      title: skill.name,
      icon: skill.icon,
      activate: () => {
        const target = workspace.sessionList().find((s) => s.focused && s.visible);
        if (target) client.input(target.agentId, target.sessionId, skillInput(skill));
      },
    });
  };
  const ribbon = createRibbon({
    manage: [
      {
        label: "Skills…",
        open: () =>
          openSkillsEditor((skill, id) => {
            if (!skill) {
              knownSkills.delete(id);
              ribbon.unregister(id);
              return;
            }
            const isNew = !knownSkills.has(id);
            registerSkill(skill);
            if (isNew) ribbon.pin(id); // a freshly created skill lands on the bar
          }),
      },
      {
        label: "Extensions…",
        open: () =>
          openExtensionsManager((exts) => {
            for (const e of exts) if (!extIds.has(e.id)) freshExtIds.add(e.id);
            extIds = new Set(exts.map((e) => e.id));
            extHost.sync(exts);
          }),
      },
    ],
  });
  for (const s of loadSkills()) registerSkill(s);
  app.classList.add("has-ribbon");

  // Extensions: each enabled one runs in its own sandboxed Worker; everything
  // it can reach in Glass goes through this delegate, gated by the
  // capabilities granted at install (extension-host.ts). Buttons auto-pin
  // only for extensions installed THIS session — a re-registration on a
  // normal launch must never override the user's unpin.
  let extIds = new Set(loadExtensions().map((e) => e.id));
  const freshExtIds = new Set<string>();
  // Messages dock (plan §6): browses/answers the iMessages of whichever fleet
  // Mac serves the bridge. The ribbon widget appears only while such an agent
  // is connected; it auto-pins once (first sighting), then the user's
  // arrangement is respected. Desktop layout only (hidden <720px).
  const msgPanel = new IMessagePanel(client);
  let msgWidgetRegistered = false;
  function syncMessagesWidget(): void {
    const capable = latestDevices
      .filter((d) => d.imessagePresent === true && d.roles.includes("agent") && d.state === "connected")
      .map((d) => ({ id: d.id, name: d.name, ...(d.imessageAccount !== undefined ? { account: d.imessageAccount } : {}) }));
    msgPanel.setAgents(capable);
    if (capable.length > 0 && !msgWidgetRegistered) {
      msgWidgetRegistered = true;
      ribbon.register({ id: "messages", title: "Messages", icon: "💬", activate: () => msgPanel.toggle() });
      let pinnedOnce = false;
      try {
        pinnedOnce = localStorage.getItem("glass.imsg.pinned") === "1";
        localStorage.setItem("glass.imsg.pinned", "1");
      } catch {
        /* private mode — pin every launch rather than never */
      }
      if (!pinnedOnce) ribbon.pin("messages");
    } else if (capable.length === 0 && msgWidgetRegistered) {
      msgWidgetRegistered = false;
      ribbon.unregister("messages");
      if (msgPanel.isOpen) msgPanel.close();
    }
  }

  const extHost = new ExtensionHost({
    sessionList: () => workspace.sessionList(),
    typeInFocused: (text) => {
      const target = workspace.sessionList().find((s) => s.focused && s.visible);
      if (target) client.input(target.agentId, target.sessionId, text);
    },
    notify: (message) => {
      statusText.textContent = message;
    },
    registerButton: (id, title, icon, activate) => {
      ribbon.register({ id, title, icon, activate });
      const extId = id.split(":")[1]; // widgetId format: ext:<extId>:<buttonId>
      if (extId && freshExtIds.has(extId)) ribbon.pin(id);
    },
    unregisterButton: (id) => ribbon.unregister(id),
  });
  extHost.sync(loadExtensions());

  app.append(sidebar, workspace.el, agentBoard.el, msgPanel.el, ribbon.el, menuBtn, backdrop, updateBanner);

  async function refreshDevices(): Promise<void> {
    try {
      latestDevices = await client.listDevices();
    } catch {
      return; /* not connected yet */
    }
    agentBoard.setDevices(latestDevices);
    await refreshRemoteSessions();
    renderSidebar();
    maybeAutoOpen();
  }

  async function refreshRuns(): Promise<void> {
    try {
      const [runs, workspaces] = await Promise.all([client.listRuns(), client.listWorkspaces()]);
      agentBoard.replaceRuns(runs);
      agentBoard.restore(workspaces);
    } catch {
      /* Hub or provider may still be reconnecting; live broadcasts catch up. */
    }
  }

  /** Pull each connected agent's session list into `remote` (minus ones we hold),
   *  so a viewer sees shells opened by OTHER devices, not just its own. */
  async function refreshRemoteSessions(): Promise<void> {
    const agents = latestDevices.filter((d) => d.roles.includes("agent") && d.state === "connected");
    await Promise.all(
      agents.map(async (a) => {
        let list: Awaited<ReturnType<typeof client.listSessions>>;
        try {
          list = await client.listSessions(a.id);
        } catch {
          return;
        }
        for (const [sid, r] of remote) if (r.agentId === a.id) remote.delete(sid);
        for (const s of list) {
          if (!s.alive) continue; // already exited — nothing to attach to
          if (workspace.has(s.id)) continue; // already attached locally
          remote.set(s.id, { agentId: a.id, title: s.title });
        }
      }),
    );
  }

  /** Plan §6: open one shell on connect ONLY if the fleet has nothing to show. */
  function maybeAutoOpen(): void {
    if (didAutoOpen || workspace.sessionList().length > 0 || remote.size > 0) return;
    const agent = latestDevices.find((d) => d.roles.includes("agent") && d.state === "connected");
    if (agent) {
      didAutoOpen = true;
      void openShell(agent.id, agent.name);
    }
  }

  async function openShell(agentId: string, agentName: string): Promise<void> {
    try {
      const n = workspace.sessionList().filter((s) => s.agentId === agentId).length + 1;
      const session = await client.createSession(agentId, { kind: "pty" });
      remote.delete(session.id); // in case its own broadcast raced ahead of us
      workspace.add(session.id, agentId, `${agentName} · shell ${n}`);
      workspace.show(session.id); // switch to the new shell
      app.classList.remove("drawer-open"); // mobile: reveal the new shell
      renderSidebar();
    } catch (err) {
      statusText.textContent = `could not open shell: ${String(err)}`;
    }
  }

  /**
   * Plan §7: browse locally, egress elsewhere. Ask THIS Mac's agent for a
   * loopback SOCKS forwarder aimed at the chosen egress device, then launch an
   * isolated browser profile (one per egress device — cookie jars never cross
   * egress identities) pinned to it. Desktop only: needs the local agent and
   * the shell's launch command.
   */
  async function browseVia(egressId: string, egressName: string): Promise<void> {
    const local = extras?.localAgentId;
    if (!local) return;
    try {
      statusText.textContent = `starting proxy via ${egressName}…`;
      const port = await client.openProxyForward(local, egressId);
      await launchProxiedBrowser({ socksHost: "127.0.0.1", socksPort: port, profileName: `egress-${egressId}` });
      statusText.textContent = `browser launched — egress via ${egressName}`;
    } catch (err) {
      statusText.textContent = `browse via ${egressName} failed: ${err instanceof Error ? err.message : String(err)}`;
    }
  }

  /** Attach a session that lives on another device and bring it into the workspace. */
  async function openRemote(agentId: string, sessionId: string, title: string): Promise<void> {
    remote.delete(sessionId);
    workspace.add(sessionId, agentId, title);
    workspace.show(sessionId);
    app.classList.remove("drawer-open");
    renderSidebar();
    try {
      await client.attach(agentId, sessionId); // scrollback paints via onScrollback
    } catch (err) {
      workspace.markDead(sessionId, "could not attach");
      statusText.textContent = `could not attach: ${String(err)}`;
    }
  }

  /** After a successful session.rename, sync our local copies of the title.
   *  (Other viewers sync via the session.renamed broadcast.) */
  function applySessionRename(s: { id: string; title: string }): void {
    workspace.rename(s.id, s.title);
    const r = remote.get(s.id);
    if (r) r.title = s.title;
    renderSidebar();
  }

  /**
   * Right-click a sidebar row (session or device): swap its name for an inline
   * input. Enter or clicking away commits via `commit` (the rename rides the
   * protocol, so every device's sidebar updates from the broadcast); Esc
   * cancels; failures land in the status line.
   */
  function attachRenamer(item: HTMLElement, stitle: HTMLElement, commit: (name: string) => Promise<void>): void {
    item.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      if (item.querySelector("input")) return; // already editing
      const input = document.createElement("input");
      input.className = "session-rename";
      input.value = stitle.textContent ?? "";
      input.maxLength = 80;
      let done = false;
      const finish = (commitIt: boolean): void => {
        if (done) return;
        done = true;
        const title = input.value.trim();
        input.replaceWith(stitle);
        if (commitIt && title && title !== stitle.textContent) {
          void commit(title).catch(
            (err) => (statusText.textContent = `rename failed: ${err instanceof Error ? err.message : String(err)}`),
          );
        }
      };
      input.addEventListener("keydown", (ke) => {
        ke.stopPropagation();
        if (ke.key === "Enter") finish(true);
        else if (ke.key === "Escape") finish(false);
      });
      input.addEventListener("blur", () => finish(true));
      // Editing must not trigger the row's own click/drag behaviour.
      input.addEventListener("click", (ce) => ce.stopPropagation());
      input.addEventListener("mousedown", (ce) => ce.stopPropagation());
      stitle.replaceWith(input);
      input.focus();
      input.select();
    });
  }

  /** Sidebar: each agent (device) with its sessions nested beneath it. */
  function renderSidebar(): void {
    syncMessagesWidget();
    deviceList.replaceChildren();
    const agents = latestDevices.filter((d) => d.roles.includes("agent"));
    const sessions = workspace.sessionList();
    const remoteList = [...remote.entries()]
      .filter(([sid]) => !workspace.has(sid))
      .map(([sid, r]) => ({ sessionId: sid, agentId: r.agentId, title: r.title }));
    const agentIds = [...new Set([...agents.map((a) => a.id), ...sessions.map((s) => s.agentId), ...remoteList.map((s) => s.agentId)])];
    if (agentIds.length === 0) {
      const empty = document.createElement("div");
      empty.className = "empty";
      empty.textContent = "no agents online";
      deviceList.append(empty);
      return;
    }
    for (const agentId of agentIds) {
      const agent = agents.find((a) => a.id === agentId);
      const connected = agent?.state === "connected";

      const row = document.createElement("div");
      row.className = "device";
      row.dataset["state"] = agent?.state ?? "offline";
      const dot = document.createElement("span");
      dot.className = "dot";
      dot.title = agent?.state ?? "offline";
      const name = document.createElement("span");
      name.className = "device-name";
      name.textContent = agent?.name ?? agentId;
      // Right-click renames the DEVICE (hub/spoke) fleet-wide; only meaningful
      // for devices the hub currently knows (they're the only ones rendered
      // with a live record anyway).
      if (agent) {
        row.title = "right-click to rename this device";
        attachRenamer(row, name, (t) => client.renameDevice(agentId, t).then(() => refreshDevices()));
      }
      const newShell = document.createElement("button");
      newShell.textContent = "+ shell";
      newShell.disabled = !connected;
      newShell.addEventListener("click", () => void openShell(agentId, agent?.name ?? agentId));
      row.append(dot, name);
      // Browse-via-device (plan §7) — desktop only: needs this Mac's agent for
      // the SOCKS forwarder and the shell to launch the isolated profile.
      if (isNative() && extras?.localAgentId) {
        const browse = document.createElement("button");
        browse.className = "device-browse";
        browse.textContent = "🌐";
        browse.disabled = !connected;
        browse.title = `browse the web with “${agent?.name ?? agentId}” as egress (isolated profile)`;
        browse.addEventListener("click", () => void browseVia(agentId, agent?.name ?? agentId));
        row.append(browse);
      }
      row.append(newShell);
      deviceList.append(row);

      for (const s of sessions.filter((x) => x.agentId === agentId)) {
        const item = document.createElement("div");
        item.className = "session";
        item.draggable = true;
        item.dataset["visible"] = String(s.visible);
        item.dataset["focused"] = String(s.focused);
        const stitle = document.createElement("span");
        stitle.className = "session-title";
        stitle.textContent = s.title.replace(/^.*·\s*/, ""); // "shell N" (device shown above)
        const kill = document.createElement("button");
        kill.className = "session-kill";
        kill.textContent = "×";
        kill.title = "end this session";
        kill.addEventListener("click", (e) => {
          e.stopPropagation();
          client.closeSession(agentId, s.sessionId);
          workspace.kill(s.sessionId);
        });
        item.append(stitle, kill);
        item.title = "right-click to rename";
        attachRenamer(item, stitle, (t) => client.renameSession(agentId, s.sessionId, t).then(applySessionRename));
        item.addEventListener("click", () => {
          workspace.show(s.sessionId);
          app.classList.remove("drawer-open"); // mobile: close the drawer
        });
        item.addEventListener("dragstart", (e) => {
          e.dataTransfer?.setData(SESSION_MIME, s.sessionId);
          if (e.dataTransfer) e.dataTransfer.effectAllowed = "move";
        });
        deviceList.append(item);
      }

      // Sessions on this agent that we haven't attached yet (opened by another
      // device). Click to attach + view; × ends it remotely.
      for (const s of remoteList.filter((x) => x.agentId === agentId)) {
        const item = document.createElement("div");
        item.className = "session";
        item.dataset["remote"] = "true";
        item.dataset["visible"] = "false";
        const stitle = document.createElement("span");
        stitle.className = "session-title";
        stitle.textContent = s.title.replace(/^.*·\s*/, "") || "shell";
        const hint = document.createElement("span");
        hint.className = "session-hint";
        hint.textContent = "open";
        const kill = document.createElement("button");
        kill.className = "session-kill";
        kill.textContent = "×";
        kill.title = "end this session";
        kill.addEventListener("click", (e) => {
          e.stopPropagation();
          client.closeSession(agentId, s.sessionId);
          remote.delete(s.sessionId);
          renderSidebar();
        });
        item.append(stitle, hint, kill);
        item.title = "right-click to rename";
        attachRenamer(item, stitle, (t) => client.renameSession(agentId, s.sessionId, t).then(applySessionRename));
        item.addEventListener("click", () => void openRemote(agentId, s.sessionId, s.title));
        deviceList.append(item);
      }
    }
  }

  // --- enrollment UI (self-serve join) ---
  let joinOverlay: HTMLElement | null = null;
  function clearJoinOverlay(): void {
    joinOverlay?.remove();
    joinOverlay = null;
  }
  function joinCard(title: string, body: (card: HTMLElement) => void): void {
    clearJoinOverlay();
    const o = document.createElement("div");
    o.className = "join-overlay";
    const card = document.createElement("div");
    card.className = "join-card";
    const h = document.createElement("div");
    h.className = "join-title";
    h.textContent = title;
    card.append(h);
    body(card);
    o.append(card);
    app.append(o);
    joinOverlay = o;
  }
  function showJoinWaiting(code: string): void {
    joinCard("Waiting for approval", (card) => {
      const codeEl = document.createElement("div");
      codeEl.className = "join-code";
      codeEl.textContent = code;
      const hint = document.createElement("p");
      hint.className = "join-hint";
      hint.textContent = "On your hub, approve this device — confirm it shows this same code.";
      const cancel = document.createElement("button");
      cancel.className = "connect-back";
      cancel.textContent = "cancel";
      cancel.addEventListener("click", () => void reconfigure(app, identity));
      card.append(codeEl, hint, cancel);
    });
  }
  function showJoinDenied(): void {
    joinCard("Join declined", (card) => {
      const hint = document.createElement("p");
      hint.className = "join-hint";
      hint.textContent = "The hub declined the request or the code expired.";
      const back = document.createElement("button");
      back.className = "connect-back";
      back.textContent = "back to setup";
      back.addEventListener("click", () => void reconfigure(app, identity));
      card.append(hint, back);
    });
  }
  function showApprovalPrompt(req: { requestId: string; deviceName: string; roles: DeviceRole[]; companions: EnrollCompanion[] }): void {
    // Dedup: never stack two prompts for the same request (anti prompt-fatigue).
    app.querySelector(`.enroll-approve[data-request-id="${CSS.escape(req.requestId)}"]`)?.remove();
    const o = document.createElement("div");
    o.className = "enroll-approve";
    o.dataset["requestId"] = req.requestId;
    const title = document.createElement("div");
    title.className = "enroll-approve-title";
    title.textContent = `${req.deviceName} wants to join`;
    // Show EXACTLY what will be trusted — roles + any companion keys.
    const scope = document.createElement("p");
    scope.className = "connect-hint";
    const roleTxt = req.roles.length ? req.roles.join(", ") : "viewer";
    // Itemize each companion (role + id) so the approver sees exactly what's added.
    const compTxt = req.companions.length ? ` + ${req.companions.map((c) => `${c.roles.join("/")} ${c.deviceId}`).join(", ")}` : "";
    scope.textContent = `grants: ${roleTxt}${compTxt}`;
    const hint = document.createElement("p");
    hint.className = "connect-hint";
    hint.textContent = "Type the 6-digit code shown on that device to approve.";
    const input = document.createElement("input");
    input.className = "enroll-approve-input";
    input.inputMode = "numeric";
    input.maxLength = 6;
    input.placeholder = "code";
    input.autocomplete = "off";
    const row = document.createElement("div");
    row.className = "connect-buttons";
    const approve = document.createElement("button");
    approve.className = "connect-go";
    approve.textContent = "approve";
    approve.addEventListener("click", () => {
      const code = input.value.trim();
      if (!/^\d{6}$/.test(code)) {
        input.focus();
        return;
      }
      client.sendEnrollDecision(req.requestId, true, code);
      o.remove();
    });
    const deny = document.createElement("button");
    deny.className = "connect-back";
    deny.textContent = "deny";
    deny.addEventListener("click", () => {
      client.sendEnrollDecision(req.requestId, false);
      o.remove();
    });
    row.append(approve, deny);
    o.append(title, scope, hint, input, row);
    app.append(o);
    setTimeout(() => o.remove(), 120_000); // matches the hub's enrollment TTL
  }

  client.connect();
}

void main();
